export interface PlanSeed {
  countryCode: string;
  countryName: string;
  region: string;
  dataAmountGb: number;
  unlimitedData?: boolean;
  validityDays: number;
  priceMinorUnits: number;
  currency: string;
  isPopular?: boolean;
}

export const PLAN_SEED_DATA: PlanSeed[] = [
  {
    countryCode: 'AZ',
    countryName: 'Azerbaijan',
    region: 'Caucasus',
    dataAmountGb: 3,
    validityDays: 7,
    priceMinorUnits: 499,
    currency: 'USD',
    isPopular: true,
  },
  {
    countryCode: 'AZ',
    countryName: 'Azerbaijan',
    region: 'Caucasus',
    dataAmountGb: 10,
    validityDays: 30,
    priceMinorUnits: 1299,
    currency: 'USD',
  },
  {
    countryCode: 'GE',
    countryName: 'Georgia',
    region: 'Caucasus',
    dataAmountGb: 5,
    validityDays: 15,
    priceMinorUnits: 799,
    currency: 'USD',
    isPopular: true,
  },
  {
    countryCode: 'TR',
    countryName: 'Turkey',
    region: 'Europe',
    dataAmountGb: 5,
    validityDays: 15,
    priceMinorUnits: 899,
    currency: 'USD',
    isPopular: true,
  },
  {
    countryCode: 'TR',
    countryName: 'Turkey',
    region: 'Europe',
    dataAmountGb: 20,
    validityDays: 30,
    priceMinorUnits: 1999,
    currency: 'USD',
  },
  {
    countryCode: 'DE',
    countryName: 'Germany',
    region: 'Europe',
    dataAmountGb: 5,
    validityDays: 15,
    priceMinorUnits: 999,
    currency: 'USD',
  },
  {
    countryCode: 'FR',
    countryName: 'France',
    region: 'Europe',
    dataAmountGb: 5,
    validityDays: 15,
    priceMinorUnits: 999,
    currency: 'USD',
  },
  {
    countryCode: 'GB',
    countryName: 'United Kingdom',
    region: 'Europe',
    dataAmountGb: 10,
    validityDays: 30,
    priceMinorUnits: 1599,
    currency: 'USD',
  },
  {
    countryCode: 'ES',
    countryName: 'Spain',
    region: 'Europe',
    dataAmountGb: 10,
    validityDays: 30,
    priceMinorUnits: 1499,
    currency: 'USD',
    isPopular: true,
  },
  {
    countryCode: 'IT',
    countryName: 'Italy',
    region: 'Europe',
    dataAmountGb: 10,
    validityDays: 30,
    priceMinorUnits: 1499,
    currency: 'USD',
  },
  {
    countryCode: 'EU',
    countryName: 'Europe (30 countries)',
    region: 'Europe',
    dataAmountGb: 0,
    unlimitedData: true,
    validityDays: 30,
    priceMinorUnits: 3499,
    currency: 'USD',
    isPopular: true,
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    region: 'Americas',
    dataAmountGb: 5,
    validityDays: 15,
    priceMinorUnits: 1299,
    currency: 'USD',
    isPopular: true,
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    region: 'Americas',
    dataAmountGb: 20,
    validityDays: 30,
    priceMinorUnits: 2999,
    currency: 'USD',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    region: 'Americas',
    dataAmountGb: 5,
    validityDays: 15,
    priceMinorUnits: 1299,
    currency: 'USD',
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    region: 'Americas',
    dataAmountGb: 5,
    validityDays: 15,
    priceMinorUnits: 1099,
    currency: 'USD',
  },
  {
    countryCode: 'AE',
    countryName: 'United Arab Emirates',
    region: 'Middle East',
    dataAmountGb: 5,
    validityDays: 15,
    priceMinorUnits: 1199,
    currency: 'USD',
    isPopular: true,
  },
  {
    countryCode: 'SA',
    countryName: 'Saudi Arabia',
    region: 'Middle East',
    dataAmountGb: 5,
    validityDays: 15,
    priceMinorUnits: 1199,
    currency: 'USD',
  },
  {
    countryCode: 'JP',
    countryName: 'Japan',
    region: 'Asia',
    dataAmountGb: 5,
    validityDays: 15,
    priceMinorUnits: 1399,
    currency: 'USD',
    isPopular: true,
  },
  {
    countryCode: 'KR',
    countryName: 'South Korea',
    region: 'Asia',
    dataAmountGb: 5,
    validityDays: 15,
    priceMinorUnits: 1399,
    currency: 'USD',
  },
  {
    countryCode: 'TH',
    countryName: 'Thailand',
    region: 'Asia',
    dataAmountGb: 10,
    validityDays: 30,
    priceMinorUnits: 1599,
    currency: 'USD',
    isPopular: true,
  },
  {
    countryCode: 'SG',
    countryName: 'Singapore',
    region: 'Asia',
    dataAmountGb: 5,
    validityDays: 15,
    priceMinorUnits: 1199,
    currency: 'USD',
  },
  {
    countryCode: 'CN',
    countryName: 'China',
    region: 'Asia',
    dataAmountGb: 5,
    validityDays: 15,
    priceMinorUnits: 1599,
    currency: 'USD',
  },
  {
    countryCode: 'AU',
    countryName: 'Australia',
    region: 'Oceania',
    dataAmountGb: 5,
    validityDays: 15,
    priceMinorUnits: 1499,
    currency: 'USD',
  },
  {
    countryCode: 'GLOBAL',
    countryName: 'Global (130+ countries)',
    region: 'Global',
    dataAmountGb: 1,
    validityDays: 30,
    priceMinorUnits: 4999,
    currency: 'USD',
    isPopular: true,
  },
];
